name: Docker 

on: 
  workflow_dispatch:

jobs:
  docker-job:
    runs-on: ubuntu-latest 
    container: 
      image: node:20.3-alpine3.17 
      env: 
        API_URL: some-url.com 
      ports:
        - 80:80
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log Node & OS Version
        run: |
          node -v
          cat /etc/os-release

      - name: Log Env
        run: echo $API_URL

      - name: Run application
        run: |
          echo "Running application..."

      - name: Log node version in a step
        uses: docker://node:18.16-alpine3.17
        with:
          args: |
            - node -v
